# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 940127bd1ded5035f9c3a6af5fa80d3f8a5498b83f80fa9b8174a59f178e9eb1b6b591c2f6d6c9ca6affb76540aa9c6abfed522f1608073be0de6f5a0ccba064

test:
  secret_key_base: feac909f5dfb990dd62acf506ab32dfbb3512d5daa19788da43e27c3b60974ffcfbbc82680d3bb343b61f78759dee681cd7034c974ac948738bcfa72db15a172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
